# Generated by Django 3.2.13 on 2022-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('mean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('variance', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
