# Generated by Django 3.2.13 on 2022-09-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='title',
            field=models.CharField(default='no title', max_length=50),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
